// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.notivera.notivera_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class ConnectionType(val raw: Int) {
  ALL(0),
  WIFI(1),
  MOBILE(2),
  MOBILE_ROAMING(3),
  MOBILE_NO_ROAMING(4);

  companion object {
    fun ofRaw(raw: Int): ConnectionType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class EventType(val raw: Int) {
  NOTIFICATION_TAPPED(0),
  VIDEO_CLOSED(1),
  IN_APP_CLOSED(2),
  IN_APP_CTA_TAPPED(3);

  companion object {
    fun ofRaw(raw: Int): EventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NotiveraConfig (
  val apiKey: String,
  val apiSecret: String,
  val appVersion: String,
  val tenantId: String,
  val customerId: String? = null,
  val inAppOpenDelayMs: Long? = null,
  val enableDebug: Boolean? = null,
  val trackLocation: Boolean? = null,
  val enableGeofence: Boolean? = null,
  val downloadConnectionType: ConnectionType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotiveraConfig {
      val apiKey = pigeonVar_list[0] as String
      val apiSecret = pigeonVar_list[1] as String
      val appVersion = pigeonVar_list[2] as String
      val tenantId = pigeonVar_list[3] as String
      val customerId = pigeonVar_list[4] as String?
      val inAppOpenDelayMs = pigeonVar_list[5] as Long?
      val enableDebug = pigeonVar_list[6] as Boolean?
      val trackLocation = pigeonVar_list[7] as Boolean?
      val enableGeofence = pigeonVar_list[8] as Boolean?
      val downloadConnectionType = pigeonVar_list[9] as ConnectionType?
      return NotiveraConfig(apiKey, apiSecret, appVersion, tenantId, customerId, inAppOpenDelayMs, enableDebug, trackLocation, enableGeofence, downloadConnectionType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      apiSecret,
      appVersion,
      tenantId,
      customerId,
      inAppOpenDelayMs,
      enableDebug,
      trackLocation,
      enableGeofence,
      downloadConnectionType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NotiveraConfig
    return MessagesPigeonUtils.deepEquals(this.apiKey, other.apiKey) && MessagesPigeonUtils.deepEquals(this.apiSecret, other.apiSecret) && MessagesPigeonUtils.deepEquals(this.appVersion, other.appVersion) && MessagesPigeonUtils.deepEquals(this.tenantId, other.tenantId) && MessagesPigeonUtils.deepEquals(this.customerId, other.customerId) && MessagesPigeonUtils.deepEquals(this.inAppOpenDelayMs, other.inAppOpenDelayMs) && MessagesPigeonUtils.deepEquals(this.enableDebug, other.enableDebug) && MessagesPigeonUtils.deepEquals(this.trackLocation, other.trackLocation) && MessagesPigeonUtils.deepEquals(this.enableGeofence, other.enableGeofence) && MessagesPigeonUtils.deepEquals(this.downloadConnectionType, other.downloadConnectionType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.apiSecret)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tenantId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.customerId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.inAppOpenDelayMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableDebug)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.trackLocation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableGeofence)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.downloadConnectionType)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PersonalisationEntry (
  val name: String,
  val value: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PersonalisationEntry {
      val name = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as String?
      return PersonalisationEntry(name, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PersonalisationEntry
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PushEvent (
  val id: String,
  val eventType: EventType? = null,
  val title: String? = null,
  val description: String? = null,
  val replacements: String? = null,
  val message: String? = null,
  val clientMetadata: String? = null,
  val type: String? = null,
  val targetUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PushEvent {
      val id = pigeonVar_list[0] as String
      val eventType = pigeonVar_list[1] as EventType?
      val title = pigeonVar_list[2] as String?
      val description = pigeonVar_list[3] as String?
      val replacements = pigeonVar_list[4] as String?
      val message = pigeonVar_list[5] as String?
      val clientMetadata = pigeonVar_list[6] as String?
      val type = pigeonVar_list[7] as String?
      val targetUrl = pigeonVar_list[8] as String?
      return PushEvent(id, eventType, title, description, replacements, message, clientMetadata, type, targetUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      eventType,
      title,
      description,
      replacements,
      message,
      clientMetadata,
      type,
      targetUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PushEvent
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.eventType, other.eventType) && MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.description, other.description) && MessagesPigeonUtils.deepEquals(this.replacements, other.replacements) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.clientMetadata, other.clientMetadata) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.targetUrl, other.targetUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.eventType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.description)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.replacements)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientMetadata)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.targetUrl)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConnectionType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EventType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotiveraConfig.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PersonalisationEntry.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConnectionType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is EventType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NotiveraConfig -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PersonalisationEntry -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PushEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NotiveraHostApi {
  fun initialize(config: NotiveraConfig)
  fun getDeviceId(): String?
  fun getCustomerId(): String?
  fun setCustomerId(customerId: String)
  fun getSdkVersion(): String?
  fun subscribeTag(tag: String, callback: (Result<String>) -> Unit)
  fun unsubscribeTag(tag: String, callback: (Result<String>) -> Unit)
  fun updatePersonalisationVariables(entries: List<PersonalisationEntry>, callback: (Result<String>) -> Unit)
  fun getAllPersonalisations(): List<PersonalisationEntry>
  fun showInAppNotification(customIdentifier: String, callback: (Result<String>) -> Unit)
  fun closeNotificationView()
  fun requestAuthorisationPrompts(callback: (Result<Unit>) -> Unit)
  fun setPushToken(token: String)
  fun isNotiveraMessage(data: Map<String, String>): Boolean
  fun handlePushMessage(data: Map<String, String>)

  companion object {
    /** The codec used by NotiveraHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `NotiveraHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NotiveraHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as NotiveraConfig
            val wrapped: List<Any?> = try {
              api.initialize(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getDeviceId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDeviceId())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getCustomerId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCustomerId())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.setCustomerId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val customerIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setCustomerId(customerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getSdkVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSdkVersion())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.subscribeTag$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            api.subscribeTag(tagArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.unsubscribeTag$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tagArg = args[0] as String
            api.unsubscribeTag(tagArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.updatePersonalisationVariables$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entriesArg = args[0] as List<PersonalisationEntry>
            api.updatePersonalisationVariables(entriesArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getAllPersonalisations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAllPersonalisations())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.showInAppNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val customIdentifierArg = args[0] as String
            api.showInAppNotification(customIdentifierArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.closeNotificationView$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.closeNotificationView()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.requestAuthorisationPrompts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestAuthorisationPrompts{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.setPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setPushToken(tokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.isNotiveraMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dataArg = args[0] as Map<String, String>
            val wrapped: List<Any?> = try {
              listOf(api.isNotiveraMessage(dataArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.handlePushMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dataArg = args[0] as Map<String, String>
            val wrapped: List<Any?> = try {
              api.handlePushMessage(dataArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class NotiveraFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NotiveraFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onPushEvent(eventArg: PushEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.notivera_flutter.NotiveraFlutterApi.onPushEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
