// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum ConnectionType { all, wifi, mobile, mobileRoaming, mobileNoRoaming }

enum EventType { notificationTapped, videoClosed, inAppClosed, inAppCtaTapped }

class NotiveraConfig {
  NotiveraConfig({
    required this.apiKey,
    required this.apiSecret,
    required this.appVersion,
    required this.tenantId,
    this.customerId,
    this.inAppOpenDelayMs,
    this.enableDebug,
    this.trackLocation,
    this.enableGeofence,
    this.downloadConnectionType,
  });

  String apiKey;

  String apiSecret;

  String appVersion;

  String tenantId;

  String? customerId;

  int? inAppOpenDelayMs;

  bool? enableDebug;

  bool? trackLocation;

  bool? enableGeofence;

  ConnectionType? downloadConnectionType;

  List<Object?> _toList() {
    return <Object?>[
      apiKey,
      apiSecret,
      appVersion,
      tenantId,
      customerId,
      inAppOpenDelayMs,
      enableDebug,
      trackLocation,
      enableGeofence,
      downloadConnectionType,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NotiveraConfig decode(Object result) {
    result as List<Object?>;
    return NotiveraConfig(
      apiKey: result[0]! as String,
      apiSecret: result[1]! as String,
      appVersion: result[2]! as String,
      tenantId: result[3]! as String,
      customerId: result[4] as String?,
      inAppOpenDelayMs: result[5] as int?,
      enableDebug: result[6] as bool?,
      trackLocation: result[7] as bool?,
      enableGeofence: result[8] as bool?,
      downloadConnectionType: result[9] as ConnectionType?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NotiveraConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) &&
        _deepEquals(apiSecret, other.apiSecret) &&
        _deepEquals(appVersion, other.appVersion) &&
        _deepEquals(tenantId, other.tenantId) &&
        _deepEquals(customerId, other.customerId) &&
        _deepEquals(inAppOpenDelayMs, other.inAppOpenDelayMs) &&
        _deepEquals(enableDebug, other.enableDebug) &&
        _deepEquals(trackLocation, other.trackLocation) &&
        _deepEquals(enableGeofence, other.enableGeofence) &&
        _deepEquals(downloadConnectionType, other.downloadConnectionType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PersonalisationEntry {
  PersonalisationEntry({required this.name, this.value});

  String name;

  String? value;

  List<Object?> _toList() {
    return <Object?>[name, value];
  }

  Object encode() {
    return _toList();
  }

  static PersonalisationEntry decode(Object result) {
    result as List<Object?>;
    return PersonalisationEntry(
      name: result[0]! as String,
      value: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PersonalisationEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class PushEvent {
  PushEvent({
    required this.id,
    this.eventType,
    this.title,
    this.description,
    this.replacements,
    this.message,
    this.clientMetadata,
    this.type,
    this.targetUrl,
  });

  String id;

  EventType? eventType;

  String? title;

  String? description;

  String? replacements;

  String? message;

  String? clientMetadata;

  String? type;

  String? targetUrl;

  List<Object?> _toList() {
    return <Object?>[
      id,
      eventType,
      title,
      description,
      replacements,
      message,
      clientMetadata,
      type,
      targetUrl,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PushEvent decode(Object result) {
    result as List<Object?>;
    return PushEvent(
      id: result[0]! as String,
      eventType: result[1] as EventType?,
      title: result[2] as String?,
      description: result[3] as String?,
      replacements: result[4] as String?,
      message: result[5] as String?,
      clientMetadata: result[6] as String?,
      type: result[7] as String?,
      targetUrl: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PushEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(eventType, other.eventType) &&
        _deepEquals(title, other.title) &&
        _deepEquals(description, other.description) &&
        _deepEquals(replacements, other.replacements) &&
        _deepEquals(message, other.message) &&
        _deepEquals(clientMetadata, other.clientMetadata) &&
        _deepEquals(type, other.type) &&
        _deepEquals(targetUrl, other.targetUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ConnectionType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is EventType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NotiveraConfig) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PersonalisationEntry) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PushEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConnectionType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : EventType.values[value];
      case 131:
        return NotiveraConfig.decode(readValue(buffer)!);
      case 132:
        return PersonalisationEntry.decode(readValue(buffer)!);
      case 133:
        return PushEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NotiveraHostApi {
  /// Constructor for [NotiveraHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NotiveraHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(NotiveraConfig config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String?> getDeviceId() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getDeviceId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<String?> getCustomerId() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getCustomerId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<void> setCustomerId(String customerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.setCustomerId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[customerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String?> getSdkVersion() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getSdkVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<String> subscribeTag(String tag) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.subscribeTag$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[tag],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> unsubscribeTag(String tag) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.unsubscribeTag$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[tag],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> updatePersonalisationVariables(
    List<PersonalisationEntry> entries,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.updatePersonalisationVariables$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[entries],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<List<PersonalisationEntry>> getAllPersonalisations() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getAllPersonalisations$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<PersonalisationEntry>();
  }

  Future<String> showInAppNotification(String customIdentifier) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.showInAppNotification$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[customIdentifier],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> closeNotificationView() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.closeNotificationView$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> requestAuthorisationPrompts() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.requestAuthorisationPrompts$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setPushToken(String token) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.setPushToken$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[token],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isNotiveraMessage(Map<String, String> data) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.isNotiveraMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[data],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> handlePushMessage(Map<String, String> data) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.handlePushMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[data],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class NotiveraFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onPushEvent(PushEvent event);

  static void setUp(
    NotiveraFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.notivera_flutter.NotiveraFlutterApi.onPushEvent$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PushEvent arg_event = args[0]! as PushEvent;
          try {
            api.onPushEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
