// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum ConnectionType: Int {
  case all = 0
  case wifi = 1
  case mobile = 2
  case mobileRoaming = 3
  case mobileNoRoaming = 4
}

enum EventType: Int {
  case notificationTapped = 0
  case videoClosed = 1
  case inAppClosed = 2
  case inAppCtaTapped = 3
}

/// Android-only notification chrome for [NotiveraConfig.pushTheme].
///
/// Pass Android resource **names** (not Flutter asset paths), e.g. drawable /
/// mipmap / color names from the host app `res/` folder. Resolved natively via
/// `Resources.getIdentifier`. Ignored on iOS.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NotiveraPushTheme: Hashable {
  /// Android drawable or mipmap resource name for the status-bar icon.
  var smallIcon: String? = nil
  /// Android drawable or mipmap resource name for the large notification icon.
  var largeIcon: String? = nil
  /// Android color resource name for the notification accent.
  var color: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotiveraPushTheme? {
    let smallIcon: String? = nilOrValue(pigeonVar_list[0])
    let largeIcon: String? = nilOrValue(pigeonVar_list[1])
    let color: String? = nilOrValue(pigeonVar_list[2])

    return NotiveraPushTheme(
      smallIcon: smallIcon,
      largeIcon: largeIcon,
      color: color
    )
  }
  func toList() -> [Any?] {
    return [
      smallIcon,
      largeIcon,
      color,
    ]
  }
  static func == (lhs: NotiveraPushTheme, rhs: NotiveraPushTheme) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.smallIcon, rhs.smallIcon) && deepEqualsMessages(lhs.largeIcon, rhs.largeIcon) && deepEqualsMessages(lhs.color, rhs.color)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NotiveraPushTheme")
    deepHashMessages(value: smallIcon, hasher: &hasher)
    deepHashMessages(value: largeIcon, hasher: &hasher)
    deepHashMessages(value: color, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NotiveraConfig: Hashable {
  var apiKey: String
  var apiSecret: String
  var appVersion: String
  var tenantId: String
  var customerId: String? = nil
  var inAppOpenDelayMs: Int64? = nil
  var enableDebug: Bool? = nil
  var trackLocation: Bool? = nil
  var enableGeofence: Bool? = nil
  var downloadConnectionType: ConnectionType? = nil
  /// Android-only. Maps to native `NotiveraPushTheme` resource IDs.
  var pushTheme: NotiveraPushTheme? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotiveraConfig? {
    let apiKey = pigeonVar_list[0] as! String
    let apiSecret = pigeonVar_list[1] as! String
    let appVersion = pigeonVar_list[2] as! String
    let tenantId = pigeonVar_list[3] as! String
    let customerId: String? = nilOrValue(pigeonVar_list[4])
    let inAppOpenDelayMs: Int64? = nilOrValue(pigeonVar_list[5])
    let enableDebug: Bool? = nilOrValue(pigeonVar_list[6])
    let trackLocation: Bool? = nilOrValue(pigeonVar_list[7])
    let enableGeofence: Bool? = nilOrValue(pigeonVar_list[8])
    let downloadConnectionType: ConnectionType? = nilOrValue(pigeonVar_list[9])
    let pushTheme: NotiveraPushTheme? = nilOrValue(pigeonVar_list[10])

    return NotiveraConfig(
      apiKey: apiKey,
      apiSecret: apiSecret,
      appVersion: appVersion,
      tenantId: tenantId,
      customerId: customerId,
      inAppOpenDelayMs: inAppOpenDelayMs,
      enableDebug: enableDebug,
      trackLocation: trackLocation,
      enableGeofence: enableGeofence,
      downloadConnectionType: downloadConnectionType,
      pushTheme: pushTheme
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      apiSecret,
      appVersion,
      tenantId,
      customerId,
      inAppOpenDelayMs,
      enableDebug,
      trackLocation,
      enableGeofence,
      downloadConnectionType,
      pushTheme,
    ]
  }
  static func == (lhs: NotiveraConfig, rhs: NotiveraConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.apiKey, rhs.apiKey) && deepEqualsMessages(lhs.apiSecret, rhs.apiSecret) && deepEqualsMessages(lhs.appVersion, rhs.appVersion) && deepEqualsMessages(lhs.tenantId, rhs.tenantId) && deepEqualsMessages(lhs.customerId, rhs.customerId) && deepEqualsMessages(lhs.inAppOpenDelayMs, rhs.inAppOpenDelayMs) && deepEqualsMessages(lhs.enableDebug, rhs.enableDebug) && deepEqualsMessages(lhs.trackLocation, rhs.trackLocation) && deepEqualsMessages(lhs.enableGeofence, rhs.enableGeofence) && deepEqualsMessages(lhs.downloadConnectionType, rhs.downloadConnectionType) && deepEqualsMessages(lhs.pushTheme, rhs.pushTheme)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NotiveraConfig")
    deepHashMessages(value: apiKey, hasher: &hasher)
    deepHashMessages(value: apiSecret, hasher: &hasher)
    deepHashMessages(value: appVersion, hasher: &hasher)
    deepHashMessages(value: tenantId, hasher: &hasher)
    deepHashMessages(value: customerId, hasher: &hasher)
    deepHashMessages(value: inAppOpenDelayMs, hasher: &hasher)
    deepHashMessages(value: enableDebug, hasher: &hasher)
    deepHashMessages(value: trackLocation, hasher: &hasher)
    deepHashMessages(value: enableGeofence, hasher: &hasher)
    deepHashMessages(value: downloadConnectionType, hasher: &hasher)
    deepHashMessages(value: pushTheme, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PersonalisationEntry: Hashable {
  var name: String
  var value: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PersonalisationEntry? {
    let name = pigeonVar_list[0] as! String
    let value: String? = nilOrValue(pigeonVar_list[1])

    return PersonalisationEntry(
      name: name,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      value,
    ]
  }
  static func == (lhs: PersonalisationEntry, rhs: PersonalisationEntry) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.name, rhs.name) && deepEqualsMessages(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PersonalisationEntry")
    deepHashMessages(value: name, hasher: &hasher)
    deepHashMessages(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PushEvent: Hashable {
  var id: String
  var eventType: EventType? = nil
  var title: String? = nil
  var description: String? = nil
  var replacements: String? = nil
  var message: String? = nil
  var clientMetadata: String? = nil
  var type: String? = nil
  var targetUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PushEvent? {
    let id = pigeonVar_list[0] as! String
    let eventType: EventType? = nilOrValue(pigeonVar_list[1])
    let title: String? = nilOrValue(pigeonVar_list[2])
    let description: String? = nilOrValue(pigeonVar_list[3])
    let replacements: String? = nilOrValue(pigeonVar_list[4])
    let message: String? = nilOrValue(pigeonVar_list[5])
    let clientMetadata: String? = nilOrValue(pigeonVar_list[6])
    let type: String? = nilOrValue(pigeonVar_list[7])
    let targetUrl: String? = nilOrValue(pigeonVar_list[8])

    return PushEvent(
      id: id,
      eventType: eventType,
      title: title,
      description: description,
      replacements: replacements,
      message: message,
      clientMetadata: clientMetadata,
      type: type,
      targetUrl: targetUrl
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      eventType,
      title,
      description,
      replacements,
      message,
      clientMetadata,
      type,
      targetUrl,
    ]
  }
  static func == (lhs: PushEvent, rhs: PushEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.eventType, rhs.eventType) && deepEqualsMessages(lhs.title, rhs.title) && deepEqualsMessages(lhs.description, rhs.description) && deepEqualsMessages(lhs.replacements, rhs.replacements) && deepEqualsMessages(lhs.message, rhs.message) && deepEqualsMessages(lhs.clientMetadata, rhs.clientMetadata) && deepEqualsMessages(lhs.type, rhs.type) && deepEqualsMessages(lhs.targetUrl, rhs.targetUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PushEvent")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: eventType, hasher: &hasher)
    deepHashMessages(value: title, hasher: &hasher)
    deepHashMessages(value: description, hasher: &hasher)
    deepHashMessages(value: replacements, hasher: &hasher)
    deepHashMessages(value: message, hasher: &hasher)
    deepHashMessages(value: clientMetadata, hasher: &hasher)
    deepHashMessages(value: type, hasher: &hasher)
    deepHashMessages(value: targetUrl, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EventType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return NotiveraPushTheme.fromList(self.readValue() as! [Any?])
    case 132:
      return NotiveraConfig.fromList(self.readValue() as! [Any?])
    case 133:
      return PersonalisationEntry.fromList(self.readValue() as! [Any?])
    case 134:
      return PushEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? EventType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NotiveraPushTheme {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NotiveraConfig {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PersonalisationEntry {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PushEvent {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NotiveraHostApi {
  func initialize(config: NotiveraConfig) throws
  func getDeviceId() throws -> String?
  func getCustomerId() throws -> String?
  func setCustomerId(customerId: String) throws
  func getSdkVersion() throws -> String?
  func subscribeTag(tag: String, completion: @escaping (Result<String, Error>) -> Void)
  func unsubscribeTag(tag: String, completion: @escaping (Result<String, Error>) -> Void)
  func updatePersonalisationVariables(entries: [PersonalisationEntry], completion: @escaping (Result<String, Error>) -> Void)
  func getAllPersonalisations() throws -> [PersonalisationEntry]
  func showInAppNotification(customIdentifier: String, completion: @escaping (Result<String, Error>) -> Void)
  func closeNotificationView() throws
  func requestAuthorisationPrompts(completion: @escaping (Result<Void, Error>) -> Void)
  func setPushToken(token: String) throws
  func isNotiveraMessage(data: [String: String]) throws -> Bool
  func handlePushMessage(data: [String: String]) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NotiveraHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `NotiveraHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NotiveraHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! NotiveraConfig
        do {
          try api.initialize(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let getDeviceIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getDeviceId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceIdChannel.setMessageHandler(nil)
    }
    let getCustomerIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getCustomerId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCustomerIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCustomerId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCustomerIdChannel.setMessageHandler(nil)
    }
    let setCustomerIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.setCustomerId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCustomerIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let customerIdArg = args[0] as! String
        do {
          try api.setCustomerId(customerId: customerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCustomerIdChannel.setMessageHandler(nil)
    }
    let getSdkVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getSdkVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSdkVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSdkVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSdkVersionChannel.setMessageHandler(nil)
    }
    let subscribeTagChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.subscribeTag\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      subscribeTagChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        api.subscribeTag(tag: tagArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      subscribeTagChannel.setMessageHandler(nil)
    }
    let unsubscribeTagChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.unsubscribeTag\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unsubscribeTagChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tagArg = args[0] as! String
        api.unsubscribeTag(tag: tagArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      unsubscribeTagChannel.setMessageHandler(nil)
    }
    let updatePersonalisationVariablesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.updatePersonalisationVariables\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePersonalisationVariablesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entriesArg = args[0] as! [PersonalisationEntry]
        api.updatePersonalisationVariables(entries: entriesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updatePersonalisationVariablesChannel.setMessageHandler(nil)
    }
    let getAllPersonalisationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.getAllPersonalisations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllPersonalisationsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllPersonalisations()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllPersonalisationsChannel.setMessageHandler(nil)
    }
    let showInAppNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.showInAppNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showInAppNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let customIdentifierArg = args[0] as! String
        api.showInAppNotification(customIdentifier: customIdentifierArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showInAppNotificationChannel.setMessageHandler(nil)
    }
    let closeNotificationViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.closeNotificationView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeNotificationViewChannel.setMessageHandler { _, reply in
        do {
          try api.closeNotificationView()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeNotificationViewChannel.setMessageHandler(nil)
    }
    let requestAuthorisationPromptsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.requestAuthorisationPrompts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAuthorisationPromptsChannel.setMessageHandler { _, reply in
        api.requestAuthorisationPrompts { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAuthorisationPromptsChannel.setMessageHandler(nil)
    }
    let setPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.setPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        do {
          try api.setPushToken(token: tokenArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPushTokenChannel.setMessageHandler(nil)
    }
    let isNotiveraMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.isNotiveraMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isNotiveraMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! [String: String]
        do {
          let result = try api.isNotiveraMessage(data: dataArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isNotiveraMessageChannel.setMessageHandler(nil)
    }
    let handlePushMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notivera_flutter.NotiveraHostApi.handlePushMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handlePushMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! [String: String]
        do {
          try api.handlePushMessage(data: dataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      handlePushMessageChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NotiveraFlutterApiProtocol {
  func onPushEvent(event eventArg: PushEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class NotiveraFlutterApi: NotiveraFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onPushEvent(event eventArg: PushEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.notivera_flutter.NotiveraFlutterApi.onPushEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
